SET search_path TO public;

--Top 5 Most Popular Pickup Locations:
SELECT pickup_location_id, COUNT(*) AS ride_count
FROM "Trip"
GROUP BY pickup_location_id
ORDER BY ride_count DESC
LIMIT 5;

--Average Trip Distance by Payment Type:
SELECT pt.payment_type_name, AVG(td.trip_distance) AS average_distance
FROM "Trip" trip
JOIN "PaymentType" pt ON trip.payment_type_id = pt.payment_type_id
JOIN "TripDistance" td ON trip.trip_distance_id = td.trip_distance_id
GROUP BY pt.payment_type_name
ORDER BY average_distance DESC;

--Average Tip Amount by Rate Code:
SELECT rc.rate_code_name, AVG(trip.tip_amount) AS average_tip
FROM "Trip" trip
JOIN "RateCode" rc ON trip.rate_code_id = rc.rate_code_id
GROUP BY rc.rate_code_name
ORDER BY average_tip DESC;

--Total Revenue Generated by Each Rate Code:
SELECT rc.rate_code_name, SUM(trip.total_amount) AS total_revenue
FROM "Trip" trip
JOIN "RateCode" rc ON trip.rate_code_id = rc.rate_code_id
GROUP BY rc.rate_code_name
ORDER BY total_revenue DESC;

--Top 5 Pickup Locations by Passenger Count:
SELECT pl.pickup_location_id, pc.passenger_count, COUNT(*) AS ride_count
FROM "Trip" trip
JOIN "PickupLocation" pl ON trip.pickup_location_id = pl.pickup_location_id
JOIN "PassengerCount" pc ON trip.passenger_count_id = pc.passenger_count_id
GROUP BY pl.pickup_location_id, pc.passenger_count
ORDER BY ride_count DESC
LIMIT 5;

--Total Revenue by Passenger Count and Dropoff Location:
SELECT pc.passenger_count, dl.dropoff_location_id, SUM(trip.total_amount) AS total_revenue
FROM "Trip" trip
JOIN "PassengerCount" pc ON trip.passenger_count_id = pc.passenger_count_id
JOIN "DropoffLocation" dl ON trip.dropoff_location_id = dl.dropoff_location_id
GROUP BY pc.passenger_count, dl.dropoff_location_id
ORDER BY total_revenue DESC
